@startuml
title Credential Verification
footer Cosmos Cash: https://github.com/allinbits/cosmos-cash

<style>
activityDiagram {
  LineColor #222
  FontName sans
}
</style>
skinparam monochrome false
skinparam shadowing false

start
#white:VC SetCredential with
**Credential** as parameter;
#white:__Extract__ **Subject DID**
from Credential;
#white:__Resolve__ the **Subject DID**;
if (Can be resolved?) then (no)
    #pink:Error;
    end
else (yes)
    #white:__Extract__ the **Issuer DID**
    from Credential;
    #white:__Resolve__ the **Issuer DID**;
    if (Can ber resolved?) then (no)
        #pink:Error;
        end
    else (yes)
        #white:__Extract__ **Proof**
        from Credential;
        #white:__Extract__ **Signature**
        from Proof;
        #white:__Extract__ **Verification Method ID (VmID)**
        from Proof;
        #white:__Dereference__ the **Verification Method**
        from the Issuer DID document
        using the **VmID**;
        if (Can be dereferenced?) then (no)
            #pink:Error;
            end
        else (yes)
            if (VerificationRelationships(VmID) ∩ (Authentication,AssertionMethod) ≠ ∅) then (no)
                #pink:Error;
                end
            else (yes)
                #white:__Extract__ the **Issuer Public Key**
                from the Verification Method;
                if (Can be extracted?) then (no)
                    #pink:Error;
                    end
                else (yes)
                   #white:__Verify__ the **Signature**;
                   if (Signature matches Public key?) then (no)
                       #pink:Error;
                       end
                   else (yes)
                       #palegreen:Persist credential;
                       stop
                   endif
                endif
            endif
        endif
    endif
endif

@enduml