@startuml

title Credentials
footer Cosmos Cash: https://github.com/allinbits/cosmos-cash

<style>
activityDiagram {
  LineColor #222
  FontName sans
}
</style>
skinparam monochrome false
skinparam shadowing false

partition "Regulator Credential" {
start

#white:Actor issues a **RegulatorCredential**;
if (Actor.Address ∈ RootOfTrust ?) then (no)
    #pink:Error;
    end
else (yes)
    #white:Regulator credential issued;
    stop
endif
}

partition "Registration Credential" {
start
#white:Actor issues a **RegistrationCredential**;
if (RegistrationCredential.Issuer holds RegulatorCredential ?) then (no)
    #pink:Error;
    end
else (yes)
    #white:Registration credential issued;
    stop
endif
}

partition "License Credential" {
start
#white:Actor issues a **LicenseCredential**;
if (LicenseCredential.Issuer holds RegulatorCredential ?) then (no)
    #pink:Error;
    end
else (yes)
    if (LicenseCredential.Subject holds RegistrationCredential ?) then (no)
        #pink:Error;
        end
    else (yes)
        #white:License credential issued;
        stop
    endif
endif
}


partition "User Credential" {
start
#white:Actor issues a **UserCredential**;
if (UserCredential.Issuer holds LicenseCredential ?) then (no)
    #pink:Error;
    end
else (yes)
    #white:User credential issued;
    stop
endif
}


@enduml