@startuml
title Credential Deletion
footer Cosmos Cash: https://github.com/allinbits/cosmos-cash

<style>
activityDiagram {
  LineColor #222
  FontName sans
}
</style>
skinparam monochrome false
skinparam shadowing false

start
#white:VC DeleteCredential with
**CredentialID**, **Address**
as parameters;
#white:__Get__ **Credential**
from store with CredentialID;
if (Credential exists?) then (no)
    #pink:Error;
    end
else (yes)
    #white:__Extract__ the **Issuer Public Key**
    from the Verification Method;
    if (Can be extracted?) then (no)
        #pink:Error;
        end
    else (yes)
        #white:__Verify__ the **Signature**;
        if (Signature matches Public key?) then (no)
            #pink:Error;
            end
        else (yes)
            #palegreen:Delete credential;
            stop
        endif
    endif
endif

@enduml