@startuml

title Root of Trust
footer Cosmos Cash: https://github.com/allinbits/cosmos-cash

<style>
activityDiagram {
  LineColor #222
  FontName sans
}
</style>
skinparam monochrome false
skinparam shadowing false


start
partition "Chain Setup" {
    #lightgray:An offline ceremony between network initial stakeholders
    collects the list of addresses that are added
    to the regulator module genesis parameters:
    these addresses are the **RootOfTrust**;
}


partition "Chain Startup" {
    #white:Chain starts;
    if (RootOfTrust is empty?) then (yes)
        #pink:Error;
        end
    else (no)
        #white:Start chain;
        stop
    endif
}




@enduml