@startuml

title SSI Agents Architecture
footer Cosmos Cash: https://github.com/allinbits/cosmos-cash

<style>
archimateDiagram {
  LineColor #222
  FontName sans
}
</style>
skinparam monochrome false
skinparam shadowing false


frame "Cosmos Cash Client" {
  [Token Wallet] as tw
  [Aries Agent] as aa
  database "Aries KMS"
}

cloud " " as net1
cloud " " as net2
cloud " " as net3
cloud " " as net4
cloud " " as net5

frame "Cosmos Cash Node" {
    database "Cosmos Cash Chain" as ccc
    [Chain of Trust] as ct
    [ct] <-> [ccc]
}

[DID Resolver Driver] as drd
[Aries Cloud Agent] as aca

frame "eIDAS" {
    [eIDAS Bridge] as eb
    [eIDAS] as e
    [eb] - [e]
}


[tw] - [aa]

[aa]  <--> [net1]
[net1] <--> [aca]
[aa] --> [net2]
[aca] --> [net2]

[net2] --> [drd]

[aa]  <--> [net3]
[net3] <--> [eb]
[aca] --> [net3]



[tw] <--> [net4]
[net4] <--> [ct]

[drd] --> [net5]
[net5] --> [ccc]





@enduml