// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: identifier/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryIdentifersRequest is request type for Query/Identifers RPC method.
type QueryIdentifiersRequest struct {
	// status enables to query for validators matching a given status.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryIdentifiersRequest) Reset()         { *m = QueryIdentifiersRequest{} }
func (m *QueryIdentifiersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIdentifiersRequest) ProtoMessage()    {}
func (*QueryIdentifiersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05580bf44a1c, []int{0}
}
func (m *QueryIdentifiersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentifiersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentifiersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentifiersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentifiersRequest.Merge(m, src)
}
func (m *QueryIdentifiersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentifiersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentifiersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentifiersRequest proto.InternalMessageInfo

func (m *QueryIdentifiersRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryIdentifiersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryIdentifersResponse is response type for the Query/Identifers RPC method
type QueryIdentifiersResponse struct {
	// validators contains all the queried validators.
	DidDocuments []DidDocument `protobuf:"bytes,1,rep,name=didDocuments,proto3" json:"didDocuments"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryIdentifiersResponse) Reset()         { *m = QueryIdentifiersResponse{} }
func (m *QueryIdentifiersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIdentifiersResponse) ProtoMessage()    {}
func (*QueryIdentifiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05580bf44a1c, []int{1}
}
func (m *QueryIdentifiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentifiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentifiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentifiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentifiersResponse.Merge(m, src)
}
func (m *QueryIdentifiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentifiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentifiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentifiersResponse proto.InternalMessageInfo

func (m *QueryIdentifiersResponse) GetDidDocuments() []DidDocument {
	if m != nil {
		return m.DidDocuments
	}
	return nil
}

func (m *QueryIdentifiersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryIdentifersRequest is request type for Query/Identifers RPC method.
type QueryIdentifierRequest struct {
	// status enables to query for validators matching a given status.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryIdentifierRequest) Reset()         { *m = QueryIdentifierRequest{} }
func (m *QueryIdentifierRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIdentifierRequest) ProtoMessage()    {}
func (*QueryIdentifierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05580bf44a1c, []int{2}
}
func (m *QueryIdentifierRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentifierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentifierRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentifierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentifierRequest.Merge(m, src)
}
func (m *QueryIdentifierRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentifierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentifierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentifierRequest proto.InternalMessageInfo

func (m *QueryIdentifierRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryIdentifersResponse is response type for the Query/Identifers RPC method
type QueryIdentifierResponse struct {
	// validators contains all the queried validators.
	DidDocument DidDocument `protobuf:"bytes,1,opt,name=didDocument,proto3" json:"didDocument"`
}

func (m *QueryIdentifierResponse) Reset()         { *m = QueryIdentifierResponse{} }
func (m *QueryIdentifierResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIdentifierResponse) ProtoMessage()    {}
func (*QueryIdentifierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05580bf44a1c, []int{3}
}
func (m *QueryIdentifierResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentifierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentifierResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentifierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentifierResponse.Merge(m, src)
}
func (m *QueryIdentifierResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentifierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentifierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentifierResponse proto.InternalMessageInfo

func (m *QueryIdentifierResponse) GetDidDocument() DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return DidDocument{}
}

func init() {
	proto.RegisterType((*QueryIdentifiersRequest)(nil), "allinbits.cosmoscash.identifier.QueryIdentifiersRequest")
	proto.RegisterType((*QueryIdentifiersResponse)(nil), "allinbits.cosmoscash.identifier.QueryIdentifiersResponse")
	proto.RegisterType((*QueryIdentifierRequest)(nil), "allinbits.cosmoscash.identifier.QueryIdentifierRequest")
	proto.RegisterType((*QueryIdentifierResponse)(nil), "allinbits.cosmoscash.identifier.QueryIdentifierResponse")
}

func init() { proto.RegisterFile("identifier/query.proto", fileDescriptor_5eda05580bf44a1c) }

var fileDescriptor_5eda05580bf44a1c = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x33, 0x51, 0x17, 0x9c, 0x88, 0x87, 0x41, 0x6a, 0xa9, 0x92, 0x5d, 0x23, 0xac, 0x51,
	0x74, 0x86, 0xed, 0x1e, 0x5c, 0xaf, 0xcb, 0xa2, 0x78, 0x10, 0x34, 0x88, 0x07, 0x6f, 0x93, 0x64,
	0xcc, 0x0e, 0xb4, 0x33, 0xd9, 0xce, 0x44, 0x2c, 0xe2, 0xc5, 0x27, 0x10, 0x7c, 0x0e, 0xf1, 0x01,
	0x7c, 0x81, 0x3d, 0x16, 0xbc, 0x78, 0x12, 0x69, 0xbd, 0xf8, 0x16, 0x92, 0xcc, 0xb4, 0x49, 0x6d,
	0x25, 0xb4, 0xb7, 0x49, 0xf2, 0xfd, 0x7f, 0xdf, 0xef, 0xfb, 0x98, 0xc0, 0x0e, 0x4f, 0x99, 0xd0,
	0xfc, 0x0d, 0x67, 0x23, 0x72, 0x56, 0xb0, 0xd1, 0x18, 0xe7, 0x23, 0xa9, 0x25, 0xda, 0xa5, 0x83,
	0x01, 0x17, 0x31, 0xd7, 0x0a, 0x27, 0x52, 0x0d, 0xa5, 0x4a, 0xa8, 0x3a, 0xc5, 0x75, 0x71, 0xef,
	0x66, 0x26, 0x65, 0x36, 0x60, 0x84, 0xe6, 0x9c, 0x50, 0x21, 0xa4, 0xa6, 0x9a, 0x4b, 0xa1, 0x4c,
	0xbc, 0x77, 0xcf, 0x84, 0x48, 0x4c, 0x15, 0x33, 0x5c, 0xf2, 0xf6, 0x20, 0x66, 0x9a, 0x1e, 0x90,
	0x9c, 0x66, 0x5c, 0x54, 0xc5, 0xb6, 0xf6, 0x46, 0x43, 0xa1, 0x3e, 0xda, 0x8f, 0xd7, 0x32, 0x99,
	0xc9, 0xea, 0x48, 0xca, 0x93, 0x79, 0x1b, 0x8c, 0xe1, 0xf5, 0x17, 0x25, 0xf4, 0xe9, 0xa2, 0x5c,
	0x45, 0xec, 0xac, 0x60, 0x4a, 0xa3, 0x0e, 0xdc, 0x51, 0x9a, 0xea, 0x42, 0x75, 0xc1, 0x1e, 0x08,
	0x2f, 0x47, 0xf6, 0x09, 0x3d, 0x86, 0xb0, 0xee, 0xdc, 0x75, 0xf7, 0x40, 0xe8, 0xf5, 0xf7, 0xed,
	0x6c, 0xb8, 0xd4, 0xc4, 0x66, 0x7c, 0xab, 0x89, 0x9f, 0xd3, 0x8c, 0x59, 0x66, 0xd4, 0x48, 0x06,
	0xdf, 0x00, 0xec, 0xae, 0xf6, 0x56, 0xb9, 0x14, 0x8a, 0xa1, 0x57, 0xf0, 0x4a, 0xca, 0xd3, 0x13,
	0x99, 0x14, 0x43, 0x26, 0x74, 0xa9, 0x70, 0x21, 0xf4, 0xfa, 0xf7, 0x71, 0xcb, 0x32, 0xf1, 0x49,
	0x1d, 0x3a, 0xbe, 0x78, 0xfe, 0x73, 0xd7, 0x89, 0x96, 0x38, 0xe8, 0xc9, 0x1a, 0xf9, 0x3b, 0xad,
	0xf2, 0x46, 0x6a, 0xc9, 0x3e, 0x84, 0x9d, 0x7f, 0xe4, 0xe7, 0x7b, 0xbb, 0x0a, 0x5d, 0x9e, 0xda,
	0x9d, 0xb9, 0x3c, 0x0d, 0xe4, 0xca, 0x8a, 0x17, 0x53, 0xbe, 0x84, 0x5e, 0xc3, 0xae, 0xca, 0x6c,
	0x37, 0x64, 0x13, 0xd3, 0xff, 0xe3, 0xc2, 0x4b, 0x55, 0x47, 0xf4, 0x05, 0x40, 0xaf, 0xb1, 0x5d,
	0x74, 0xd4, 0x8a, 0xfe, 0xcf, 0x65, 0xe8, 0x3d, 0xda, 0x22, 0x69, 0x86, 0x0c, 0xee, 0x7e, 0xfc,
	0xfe, 0xfb, 0xb3, 0x7b, 0x1b, 0xdd, 0x22, 0x0b, 0x04, 0x59, 0x7b, 0x51, 0x15, 0xfa, 0x0a, 0x20,
	0xac, 0x11, 0xe8, 0xe1, 0xa6, 0x4d, 0xe7, 0xb6, 0x47, 0x9b, 0x07, 0xad, 0x2c, 0xae, 0x64, 0x43,
	0xb4, 0xdf, 0x2a, 0x4b, 0xde, 0xf3, 0xf4, 0xc3, 0xf1, 0xb3, 0xf3, 0xa9, 0x0f, 0x26, 0x53, 0x1f,
	0xfc, 0x9a, 0xfa, 0xe0, 0xd3, 0xcc, 0x77, 0x26, 0x33, 0xdf, 0xf9, 0x31, 0xf3, 0x9d, 0xd7, 0x87,
	0x19, 0xd7, 0xa7, 0x45, 0x8c, 0x13, 0x39, 0x6c, 0xb0, 0x8c, 0xcd, 0x83, 0x52, 0x87, 0xbc, 0x6b,
	0x92, 0xf5, 0x38, 0x67, 0x2a, 0xde, 0xa9, 0xfe, 0xca, 0xc3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa9, 0xd5, 0xee, 0x4a, 0x4d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Identifers queries all validators that match the given status.
	Identifiers(ctx context.Context, in *QueryIdentifiersRequest, opts ...grpc.CallOption) (*QueryIdentifiersResponse, error)
	Identifier(ctx context.Context, in *QueryIdentifierRequest, opts ...grpc.CallOption) (*QueryIdentifierResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Identifiers(ctx context.Context, in *QueryIdentifiersRequest, opts ...grpc.CallOption) (*QueryIdentifiersResponse, error) {
	out := new(QueryIdentifiersResponse)
	err := c.cc.Invoke(ctx, "/allinbits.cosmoscash.identifier.Query/Identifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Identifier(ctx context.Context, in *QueryIdentifierRequest, opts ...grpc.CallOption) (*QueryIdentifierResponse, error) {
	out := new(QueryIdentifierResponse)
	err := c.cc.Invoke(ctx, "/allinbits.cosmoscash.identifier.Query/Identifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Identifers queries all validators that match the given status.
	Identifiers(context.Context, *QueryIdentifiersRequest) (*QueryIdentifiersResponse, error)
	Identifier(context.Context, *QueryIdentifierRequest) (*QueryIdentifierResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Identifiers(ctx context.Context, req *QueryIdentifiersRequest) (*QueryIdentifiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identifiers not implemented")
}
func (*UnimplementedQueryServer) Identifier(ctx context.Context, req *QueryIdentifierRequest) (*QueryIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identifier not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Identifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentifiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Identifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allinbits.cosmoscash.identifier.Query/Identifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Identifiers(ctx, req.(*QueryIdentifiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Identifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Identifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allinbits.cosmoscash.identifier.Query/Identifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Identifier(ctx, req.(*QueryIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "allinbits.cosmoscash.identifier.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identifiers",
			Handler:    _Query_Identifiers_Handler,
		},
		{
			MethodName: "Identifier",
			Handler:    _Query_Identifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identifier/query.proto",
}

func (m *QueryIdentifiersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentifiersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentifiersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIdentifiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentifiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentifiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DidDocuments) > 0 {
		for iNdEx := len(m.DidDocuments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DidDocuments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryIdentifierRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentifierRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentifierRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIdentifierResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentifierResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentifierResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIdentifiersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIdentifiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DidDocuments) > 0 {
		for _, e := range m.DidDocuments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIdentifierRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIdentifierResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DidDocument.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIdentifiersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentifiersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentifiersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentifiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentifiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentifiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocuments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidDocuments = append(m.DidDocuments, DidDocument{})
			if err := m.DidDocuments[len(m.DidDocuments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentifierRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentifierRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentifierRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentifierResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentifierResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentifierResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
