@startjson LicenseCredential
{
	"@context": [
		"https://www.w3.org/2018/credentials/v1",
		"https://www.cosmos.cash/2021/credentials/license/v1"
	],
	"id": "did:cosmos:cash:1000bb528777",
	"type": [
		"VerifiableCredential", 
		"LicenseCredential"
	],
	"issuer": "did:sov:12345",
	"issuanceDate": "2021-08-01T15:23:24Z",
	"credentialSubject": {
		"vasp": {
			"vaspId": "did:cosmos:cash:1000bb528777",
			"legalPerson": {
				"names": [{
					"name": "Example VASP AG",
					"nametype": "LEGL"
				}, {
					"name": "EgVASP",
					"nametype": "SHRT"
				}],
				"ctryReg": "CH"
			},
			"address": {
				"adr_type": "BIZZ",
				"thfare": "Liverpool Street",
				"premise": "22",
				"postcode": "EC2R",
				"locality": "London",
				"country": "GB"
			},
			"ids": [{
				"idId": "CH02035398520",
				"idType": "RAID"
			}, {
				"idId": "529900W6B9NEA233DS71",
				"idType": "LEIX"
			}]
		},
		"licenses": [{
			"licenseType": "VQFSRO",
			"country": "CH",
			"authority": "Financial Services Standards Association (VQF)"
		},{
			"licenseType": "MICAEMI",
			"country": "CH",
			"authority": "Another Financial Services Body (AFFB)",
			"attributes": {
				"denom": "sEUR",
				"circulationLimit": "100.0"
			}
		}],
		"agreement": {
			"type": "NetworkAgreement_v1.0",
			"mf": "ALL"
		}
	},
	"proof": {
		"type": "RsaSignature2018",
		"created": "2021-08-01T15:23:24Z",
		"proofPurpose": "assertionMethod",
		"verificationMethod": "https://example.edu/issuers/keys/1",
		"jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..."
  	}
}
@endjson

