@startjson LicenseCredential
{
	"@context": [
		"https://www.w3.org/2018/credentials/v1",
		"https://www.cosmos.cash/2021/credentials/license/v1"
	],
	"id": "http://fca.gov.uk/credentials/1234",
	"type": [
		"VerifiableCredential", 
		"LicenseCredential"
	],
	"issuer": "did:sov:12345",
	"issuanceDate": "2021-08-01T15:23:24Z",
	"credentialSubject": {
      "id": "did:cosmos:cash:1000bb528777",
      "license": {
        "licenseType": "MICAEMI",
        "country": "CH",
        "authority": "Another Financial Services Body (AFSB)",
        "denom": "sEUR",
        "circulationLimit": 100
      }
	},
	"proof": {
		"type": "SIGNATURE_TYPE",
		"created": "2021-08-01T15:23:24Z",
		"proofPurpose": "assertionMethod",
		"verificationMethod": "https://example.edu/issuers/keys/1",
		"jws": "jws123.."
  }
}
@endjson

