@startjson RegistrationCredential
{
	"@context": [
		"https://www.w3.org/2018/credentials/v1",
		"https://www.cosmos.cash/2021/credentials/registration/v1"
	],
	"id": "http://fca.gov.uk/credentials/1234",
	"type": [
		"VerifiableCredential", 
		"RegistrationCredential"
	],
	"issuer": "did:sov:12345",
	"issuanceDate": "2021-08-01T15:23:24Z",
	"credentialSubject": {
		"id": "did:cosmos:cash:1000bb528777",
		"legalPerson": {
			"names": [{
				"name": "Example VASP AG",
				"type": "LEGL"
			}, {
				"name": "EgVASP",
				"type": "SHRT"
			}],
			"ctryReg": "CH"
		},
		"address": {
			"addr_type": "BIZZ",
			"thfare": "Liverpool Street",
			"premise": "22",
			"postcode": "EC2R",
			"locality": "London",
			"country": "GB"
		},
		"ids": [{
			"id": "CH02035398520",
			"type": "RAID"
		}, {
			"id": "529900W6B9NEA233DS71",
			"type": "LEIX"
		}]
	},
	"proof": {
		"type": "SIGNATURE-TYPE",
		"created": "2021-08-01T15:23:24Z",
		"proofPurpose": "assertionMethod",
		"verificationMethod": "https://example.edu/issuers/keys/1",
		"jws": "a_jws_..."
  	}
}
@endjson

