// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verifiable-credential-service/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryIdentifersRequest is request type for Query/Identifers RPC method.
type QueryVerifiableCredentialsRequest struct {
	// status enables to query for credentials matching a given status.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVerifiableCredentialsRequest) Reset()         { *m = QueryVerifiableCredentialsRequest{} }
func (m *QueryVerifiableCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialsRequest) ProtoMessage()    {}
func (*QueryVerifiableCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a1f9284e9078ab, []int{0}
}
func (m *QueryVerifiableCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialsRequest.Merge(m, src)
}
func (m *QueryVerifiableCredentialsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialsRequest proto.InternalMessageInfo

func (m *QueryVerifiableCredentialsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryVerifiableCredentialsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryIdentifersResponse is response type for the Query/Identifers RPC method
type QueryVerifiableCredentialsResponse struct {
	// validators contains all the queried validators.
	Vcs []VerifiableCredential `protobuf:"bytes,1,rep,name=vcs,proto3" json:"vcs"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVerifiableCredentialsResponse) Reset()         { *m = QueryVerifiableCredentialsResponse{} }
func (m *QueryVerifiableCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialsResponse) ProtoMessage()    {}
func (*QueryVerifiableCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85a1f9284e9078ab, []int{1}
}
func (m *QueryVerifiableCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialsResponse.Merge(m, src)
}
func (m *QueryVerifiableCredentialsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialsResponse proto.InternalMessageInfo

func (m *QueryVerifiableCredentialsResponse) GetVcs() []VerifiableCredential {
	if m != nil {
		return m.Vcs
	}
	return nil
}

func (m *QueryVerifiableCredentialsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryVerifiableCredentialsRequest)(nil), "allinbits.cosmoscash.verifiablecredentialservice.QueryVerifiableCredentialsRequest")
	proto.RegisterType((*QueryVerifiableCredentialsResponse)(nil), "allinbits.cosmoscash.verifiablecredentialservice.QueryVerifiableCredentialsResponse")
}

func init() {
	proto.RegisterFile("verifiable-credential-service/query.proto", fileDescriptor_85a1f9284e9078ab)
}

var fileDescriptor_85a1f9284e9078ab = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x6a, 0xdb, 0x30,
	0x00, 0x86, 0x2d, 0x67, 0x0b, 0x4c, 0xb9, 0x89, 0x6d, 0x84, 0x30, 0xbc, 0xcc, 0x87, 0x2d, 0x1b,
	0x44, 0x5a, 0x32, 0x18, 0xdb, 0x65, 0x87, 0x0c, 0xb2, 0xeb, 0xe6, 0x95, 0x1e, 0x7a, 0x28, 0x95,
	0x5d, 0xd5, 0x11, 0x38, 0x96, 0x63, 0xc9, 0xa6, 0xb9, 0xa6, 0xd7, 0x1e, 0x0a, 0x7d, 0xa9, 0x5c,
	0x0a, 0x81, 0x5e, 0x7a, 0x2a, 0x25, 0xe9, 0x83, 0x14, 0xdb, 0x22, 0xce, 0xc1, 0x24, 0x04, 0x7a,
	0x93, 0x65, 0xfd, 0x9f, 0xbe, 0x5f, 0x12, 0xfc, 0x9c, 0xb2, 0x98, 0x9f, 0x71, 0xea, 0x06, 0xac,
	0xeb, 0xc5, 0xec, 0x94, 0x85, 0x8a, 0xd3, 0xa0, 0x2b, 0x59, 0x9c, 0x72, 0x8f, 0x91, 0x49, 0xc2,
	0xe2, 0x29, 0x8e, 0x62, 0xa1, 0x04, 0xfa, 0x4a, 0x83, 0x80, 0x87, 0x2e, 0x57, 0x12, 0x7b, 0x42,
	0x8e, 0x85, 0xf4, 0xa8, 0x1c, 0xe1, 0x32, 0x5f, 0xc6, 0x75, 0xba, 0xf5, 0xce, 0x17, 0xc2, 0x0f,
	0x18, 0xa1, 0x11, 0x27, 0x34, 0x0c, 0x85, 0xa2, 0x8a, 0x8b, 0x50, 0x16, 0xbc, 0xd6, 0x97, 0x82,
	0x42, 0x5c, 0x2a, 0xf5, 0x46, 0x24, 0xed, 0xb9, 0x4c, 0xd1, 0x1e, 0x89, 0xa8, 0xcf, 0xc3, 0x7c,
	0xb1, 0x5e, 0xfb, 0x73, 0xbb, 0x66, 0xe5, 0x5f, 0x1d, 0x7d, 0xed, 0x0b, 0x5f, 0xe4, 0x43, 0x92,
	0x8d, 0x8a, 0x59, 0xfb, 0x02, 0xc0, 0x0f, 0xff, 0xb2, 0x3d, 0x0f, 0xd7, 0xd1, 0xdf, 0xa5, 0xbf,
	0xc3, 0x26, 0x09, 0x93, 0x0a, 0xbd, 0x85, 0x75, 0xa9, 0xa8, 0x4a, 0x64, 0x13, 0xb4, 0x41, 0xe7,
	0x95, 0xa3, 0xbf, 0xd0, 0x10, 0xc2, 0x52, 0xb1, 0x69, 0xb6, 0x41, 0xa7, 0xd1, 0xff, 0xa8, 0x4f,
	0x05, 0x67, 0x7d, 0x70, 0x71, 0x70, 0xba, 0x0f, 0xfe, 0x4b, 0x7d, 0xa6, 0x99, 0xce, 0x46, 0xd2,
	0xbe, 0x01, 0xd0, 0xde, 0x66, 0x21, 0x23, 0x11, 0x4a, 0x86, 0x8e, 0x61, 0x2d, 0xf5, 0x32, 0x87,
	0x5a, 0xa7, 0xd1, 0x1f, 0xe2, 0x7d, 0xef, 0x01, 0x57, 0xd1, 0x07, 0x2f, 0xe6, 0xf7, 0xef, 0x0d,
	0x27, 0x03, 0xa3, 0x3f, 0x15, 0x75, 0x3e, 0xed, 0xac, 0x53, 0xc8, 0x6d, 0xf6, 0xe9, 0x5f, 0x9a,
	0xf0, 0x65, 0xde, 0x07, 0xcd, 0x4c, 0xf8, 0xa6, 0xb2, 0x14, 0xfa, 0xbf, 0xbf, 0xff, 0xce, 0x8b,
	0x6a, 0x1d, 0x3c, 0x2f, 0xb4, 0xa8, 0x66, 0xff, 0x9a, 0xdd, 0x3e, 0x5e, 0x9b, 0x3f, 0xd0, 0x77,
	0xb2, 0xa6, 0x93, 0x4a, 0x64, 0xf5, 0xec, 0xe0, 0x64, 0xbe, 0xb4, 0xc0, 0x62, 0x69, 0x81, 0x87,
	0xa5, 0x05, 0xae, 0x56, 0x96, 0xb1, 0x58, 0x59, 0xc6, 0xdd, 0xca, 0x32, 0x8e, 0x86, 0x3e, 0x57,
	0xa3, 0xc4, 0xc5, 0x9e, 0x18, 0x6f, 0xb0, 0x0b, 0xf3, 0x6e, 0xa6, 0x4e, 0xce, 0xc9, 0xf6, 0x27,
	0xaf, 0xa6, 0x11, 0x93, 0x6e, 0x3d, 0x7f, 0xcd, 0xdf, 0x9e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8,
	0x99, 0xcd, 0x27, 0xc7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Identifers queries all validators that match the given status.
	VerifiableCredentials(ctx context.Context, in *QueryVerifiableCredentialsRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) VerifiableCredentials(ctx context.Context, in *QueryVerifiableCredentialsRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialsResponse, error) {
	out := new(QueryVerifiableCredentialsResponse)
	err := c.cc.Invoke(ctx, "/allinbits.cosmoscash.verifiablecredentialservice.Query/VerifiableCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Identifers queries all validators that match the given status.
	VerifiableCredentials(context.Context, *QueryVerifiableCredentialsRequest) (*QueryVerifiableCredentialsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) VerifiableCredentials(ctx context.Context, req *QueryVerifiableCredentialsRequest) (*QueryVerifiableCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifiableCredentials not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_VerifiableCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifiableCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifiableCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allinbits.cosmoscash.verifiablecredentialservice.Query/VerifiableCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifiableCredentials(ctx, req.(*QueryVerifiableCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "allinbits.cosmoscash.verifiablecredentialservice.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifiableCredentials",
			Handler:    _Query_VerifiableCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verifiable-credential-service/query.proto",
}

func (m *QueryVerifiableCredentialsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifiableCredentialsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vcs) > 0 {
		for iNdEx := len(m.Vcs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vcs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryVerifiableCredentialsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifiableCredentialsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Vcs) > 0 {
		for _, e := range m.Vcs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryVerifiableCredentialsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifiableCredentialsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vcs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vcs = append(m.Vcs, VerifiableCredential{})
			if err := m.Vcs[len(m.Vcs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
